### PR TITLE
Update to tensorflow 1.14

### PR DESCRIPTION
**Pull request by timmccor**
Updates Tensorflow to 1.14.

[configure.py at Tensorflow 1.14](https://github.com/tensorflow/tensorflow/blob/v1.14.0/configure.py) requires a Bazel between version 0.24.1 and 0.25.2 to build, so update that too.

I have no way to test this Docker file, but I'm hoping this PR will trigger the azure pipeline to go try it.

### CODE REVIEW

**Comment by pvizeli** [comment]
This will not work. I already try this and end up on many issues. TensorFlow is nice to run but a Norse if you want build it.

**Comment by timmccor** [comment]
What errors do you get @pvizeli ? I've built this on my own system without too much pain. Is there any way I can run this through the Azure pipeline? I don't have any Linux systems with which I can run a Docker container unfortunately for test purposes.

**Comment by frenck** [comment]
The problem, in general, is the cross-architecture builds

**Comment by timmccor** [comment]
The problem is that tensorflow 1.14 added a call to pthread_getname_np(), and the libc used by Alpine 'musl' does not support this function at any version.

It is therefore no longer possible to compile a v1 tensorflow newer than 1.13 on Alpine Linux. Tensorflow 2 doesn't contain the [tensorflow/tensorflow/core/platform/posix/env.cc](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/platform/posix/env.cc) file which contains this function call, so it may be possible to compile that. Or perhaps they just moved the function to another file.

The owner of musl [suggested ](https://www.openwall.com/lists/musl/2019/07/17/3)that this function would be added in future in July 2019, but this hasn't happened and the head of that codebase still does not contain it.

Any suggestions on how to progress, as I assume there is no ability to move away from Alpine for our wheels?

**Comment by frenck** [comment]
We can't move away from Alpine indeed, so that is no option.
Tensorflow 2 might be an option, but that needs work on multiple ends. Feel free to take a shot at that :+1:

**Comment by timmccor** [comment]
Closing as there is no way to get tensorflow 1.14 to build in Alpine

**Comment by timmccor** [comment]
In the meantime, perhaps we should revisit the need to pin tensorflow to a specific version? It's problematic to build at some versions on some platforms, and subsequently some users are unable to build what they need at the arbitrary version we've picked. *Especially* if Alpine is unable to build any of the new v1 versions.

**Comment by timmccor** [comment]
Poking around tensorflow, I can see that we will hit the [same problem](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/env.cc) in tensorflow 2 as well.

So the only solutions I can think of are:

1. Submit a PR to tensorflow to ifdef out the call to pthread_getname_np when using musl. Not sure how feasible this is.

1. Submit a PR to musl to add the missing pthread_getname_np function

1. Switch the Alpine we're using to use a non-default libc, glibc for example

1. Move to a different Linux distribution which uses a different libc

**Comment by pvizeli** [comment]
The only way is to patch that function with a macro. Maybe someone provide allready a patch, otherwise we need self write a macro to aim that function

**Comment by timmccor** [comment]
Well, option 1 and 2 are equally plausible and neither should be that hard. But you really want it in the proper repo rather than maintaining a patch forever more.

The main issue with 1 is identifying the consequences of not providing the result you get on other Linux distributions. Macros are generally undesirable as they make the code harder to understand, and they're generally not considered when new function is being written.

The ideal solution is to contribute the missing code to Musl.

**Pull request closed without merging**
